# -*- coding: utf-8 -*-
"""Coffeemaker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voxiuAeuCM2ol9SEbUWP2YhPctT-fuip
"""

#menu
import sys
print("Welcome to my Coffee Shop:")
print("\n** MENU **")
print("\n--- Sizes ---")
print("   Small")
print("   Medium")
print("   Large")
print("\n--- Styles ---")
print("   Espresso")
print("   Cappuccino")
print("   Latte")
print("\n--------------------------")
#Order
sizeInput = input("What SIZE of Coffee? ")
styleInput = input("What TYPE of Coffee? ")
size = sizeInput.lower()
style = styleInput.lower()
#Proccesing Order
match style:
  case "cappuccino":
    finalOrderStyle = "cappuccino"
  case "espresso":
    finalOrderStyle = "espresso"
  case "latte":
    finalOrderStyle = "latte"
  case _:
    sys.exit("Invalid Style")
match size:
  case "large":
    finalOrderSize = "large"
  case "medium":
    finalOrderSize = "medium"
  case "small":
    finalOrderSize = "small"
  case _:
    sys.exit("Invalid Size")
#Putting out Order
print(f"\nYour order is a {finalOrderSize} {finalOrderStyle}.")